{
  "hash": "47ceb325364f602fac7bbae44d1e1f04",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Step 1: Population structure within species\"\nsubtitle: Vocal character displacement in southern capuchinos\nauthor: <a href=\"https://marce10.github.io/\">Marcelo Araya-Salas</a>\ndate: \"2026-10-08\"\ntoc: true\ntoc-depth: 4\ntoc-location: left\nnumber-sections: true\nhighlight-style: pygments\nformat:\n  html:\n    df-print: kable\n    code-fold: true\n    code-tools: true\n    css: qmd.css\neditor_options: \n  chunk_output_type: console\n---\n\n\n::: {.cell}\n\n:::\n\n\n\nSource code and data found at [https://github.com/maRce10/vocal_character_displacement_in_southern_capuchinos](https://github.com/maRce10/vocal_character_displacement_in_southern_capuchinos)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# options to customize chunk outputs\nknitr::opts_chunk$set(\n  message = FALSE\n)\n```\n:::\n\n\n<!-- skyblue box -->\n\n::: {.alert .alert-info}\n# Purpose {.unnumbered .unlisted}\n\n-   Evaluate how much each species' song varies across its range\n-   Test whether songs are more similar within than between populations, and whether acoustic distance increases with geographic distance (isolation by distance)\n:::\n\nDo songs vary across each species' range, and is that variation organized by population? Here we compare songs of different individuals of the same species recorded in the same population with those recorded in different populations. If songs are population-structured, within-population pairs should be more similar (smaller acoustic distance) than between-population pairs. This also shows that there is local variation on which sympatry could act (Step 3).\n\nAcoustic distance is the same PCA-based Euclidean distance used in the sympatry models. Pairs of songs from the same individual are excluded.\n\n# Load packages and custom functions {.unnumbered .unlisted}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# install knitr package if not installed\nif (!requireNamespace(\"sketchy\", quietly = TRUE)) {\n  install.packages(\"sketchy\")\n}\n\npackages <- c(\n  \"knitr\",\n  \"dplyr\",\n  \"tidyverse\",\n  \"vegan\",\n  \"ecodist\",\n  \"brms\",\n  github = \"maRce10/brmsish\",\n  \"kableExtra\",\n  \"ggplot2\",\n  \"ggtext\",\n  \"ggh4x\",\n  github = \"stan-dev/cmdstanr\"\n)\n\n# install/load packages\nsketchy::load_packages(packages = packages)\n\noptions(knitr.kable.NA = '', brms.file_refit = \"never\")\n\n# set theme globally\ntheme_set(theme_classic(base_size = 20))\n\n# custom functions (shared by all reports)\nsource(\"./scripts/functions.R\")\n```\n:::\n\n\n# Load data {.unnumbered .unlisted}\n\nPairwise data sets created in [Data preparation](0_data_preparation.qmd).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstep_inputs_simple <- readRDS(\"./data/processed/step_inputs_simple.rds\")\nps_dat_simple <- step_inputs_simple$ps_dat\nocc_simple <- step_inputs_simple$occ\n\nstep_inputs_complex <- readRDS(\"./data/processed/step_inputs_complex.rds\")\nps_dat_complex <- step_inputs_complex$ps_dat\nocc_complex <- step_inputs_complex$occ\n```\n:::\n\n\n# Simple songs\n\nRange-wide variation by species (`mean_within` and `mean_between` are mean acoustic distances among songs of different individuals within and between populations; the ratio is > 1 when songs are population-structured):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(population_structure_summary(ps_dat_simple))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div style=\"border: 1px solid #ddd; padding: 5px; overflow-x: scroll; width:100%; \"><table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> species </th>\n   <th style=\"text-align:right;\"> populations </th>\n   <th style=\"text-align:right;\"> individuals </th>\n   <th style=\"text-align:right;\"> within_population_pairs </th>\n   <th style=\"text-align:right;\"> between_population_pairs </th>\n   <th style=\"text-align:right;\"> mean_within </th>\n   <th style=\"text-align:right;\"> mean_between </th>\n   <th style=\"text-align:right;\"> between_within_ratio </th>\n   <th style=\"text-align:right;\"> max_geo_distance_km </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Hypoxantha </td>\n   <td style=\"text-align:right;\"> 3 </td>\n   <td style=\"text-align:right;\"> 30 </td>\n   <td style=\"text-align:right;\"> 7235 </td>\n   <td style=\"text-align:right;\"> 10076 </td>\n   <td style=\"text-align:right;\"> 1.923 </td>\n   <td style=\"text-align:right;\"> 2.127 </td>\n   <td style=\"text-align:right;\"> 1.106 </td>\n   <td style=\"text-align:right;\"> 582 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Iberaensis </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 5 </td>\n   <td style=\"text-align:right;\"> 103 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 1.731 </td>\n   <td style=\"text-align:right;\">  </td>\n   <td style=\"text-align:right;\">  </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Palustris </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 12 </td>\n   <td style=\"text-align:right;\"> 359 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 1.553 </td>\n   <td style=\"text-align:right;\">  </td>\n   <td style=\"text-align:right;\">  </td>\n   <td style=\"text-align:right;\"> 9 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Ruficollis </td>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:right;\"> 32 </td>\n   <td style=\"text-align:right;\"> 4045 </td>\n   <td style=\"text-align:right;\"> 11412 </td>\n   <td style=\"text-align:right;\"> 1.447 </td>\n   <td style=\"text-align:right;\"> 2.424 </td>\n   <td style=\"text-align:right;\"> 1.675 </td>\n   <td style=\"text-align:right;\"> 1159 </td>\n  </tr>\n</tbody>\n</table></div>\n\n`````\n:::\n:::\n\n\nSpecies sampled at a single locality only contribute within-population variation, so they are described above but not included in the models below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(ps_dat_simple, aes(x = same_population, y = acoustic_distance, fill = same_population)) +\n  geom_violin(alpha = 0.6, color = NA) +\n  geom_boxplot(width = 0.15, outlier.shape = NA, fill = \"white\") +\n  facet_wrap(~ species, nrow = 1) +\n  scale_x_discrete(labels = c(\"0\" = \"Between populations\", \"1\" = \"Within population\")) +\n  scale_fill_viridis_d(option = \"mako\", begin = 0.3, end = 0.8, guide = \"none\") +\n  labs(x = NULL, y = \"Acoustic distance\") +\n  theme(axis.text.x = element_text(size = rel(0.7), angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](1_population_structure_files/figure-html/population structure plot simple-1.png){width=672}\n:::\n:::\n\n\n## Model: within vs. between populations\n\n$$\n\\begin{split}\n\\text{acoustic distance} &\\sim \\text{species} + \\text{species} : \\text{same population} \\\\\n&\\quad + (1 \\mid \\text{mm(population}_1,\\text{population}_2)) \\\\\n&\\quad + (1 \\mid \\text{mm(individual}_1,\\text{individual}_2))\n\\end{split}\n$$\n\n-   Only conspecific pairs from species sampled in more than one population.\n-   `species:same_population1` is the species-specific difference in acoustic distance between within- and between-population pairs. Negative values mean songs are more similar within populations.\n-   Species enter as fixed effects because only two species have more than one population. The intercept is the baseline (between-population) distance of the reference species and `species` is the baseline difference of the other species. This parameterization keeps the regularizing prior on the effects and the baseline difference only, not on species means.\n-   Multi-membership random effects for population and individual, as in the sympatry models.\n-   The response is standardized within the model dataset (both species pooled), so effects are in SD units. Regularizing priors as in the trait-level sympatry models: normal(0, 1) for the intercept, normal(0, 0.5) for fixed effects, exponential(2) for random-effect SDs (including the multi-membership terms) and exponential(1) for the residual SD.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nps_model_dat_simple <- ps_dat_simple[\n  ps_dat_simple$species %in% names(occ_simple)[lengths(occ_simple) > 1], ]\nps_model_dat_simple$species <- droplevels(ps_model_dat_simple$species)\nps_model_dat_simple$acoustic_distance_sc <- as.numeric(scale(ps_model_dat_simple$acoustic_distance))\n\npopulation_structure_model_simple <- brm(\n  acoustic_distance_sc ~ species + species:same_population +\n    (1 | mm(pop1, pop2)) +\n    (1 | mm(individual1, individual2)),\n  data = ps_model_dat_simple,\n  family = gaussian(),\n  prior = priors_ws,\n  cores = 4,\n  chains = 4,\n  iter = 10000,\n  backend = \"cmdstanr\",\n  threads = threading(8),\n  control = list(adapt_delta = 0.95, max_treedepth = 15),\n  file = \"./data/processed/fits/population_structure_simple_fit\"\n)\n```\n:::\n\n\nPrior predictive check (priors only, likelihood ignored; the observed standardized distances should fall comfortably within the range the priors generate):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprior_only_population_structure_simple <- brm(\n  acoustic_distance_sc ~ species + species:same_population +\n    (1 | mm(pop1, pop2)) +\n    (1 | mm(individual1, individual2)),\n  data = ps_model_dat_simple,\n  family = gaussian(),\n  prior = priors_ws,\n  sample_prior = \"only\",\n  chains = 2,\n  iter = 2000,\n  cores = 2,\n  seed = 123,\n  backend = \"cmdstanr\",\n  file = \"./data/processed/fits/prior_only_population_structure_simple\"\n)\n\nprior_check_plot(prior_only_population_structure_simple,\n                 \"Prior predictive check (simple songs, population structure model)\")\n```\n\n::: {.cell-output-display}\n![](1_population_structure_files/figure-html/prior predictive check population structure simple-1.png){width=672}\n:::\n:::\n\n\n\n```{.r .cell-code}\nextended_summary(\n  population_structure_model_simple,\n  highlight = TRUE,\n  trace.palette = viridis::mako,\n  remove.intercepts = TRUE,\n  print.name = FALSE\n)\n```\n\n<table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"font-size: 12px; width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:left;\"> priors </th>\n   <th style=\"text-align:left;\"> formula </th>\n   <th style=\"text-align:right;\"> iterations </th>\n   <th style=\"text-align:right;\"> chains </th>\n   <th style=\"text-align:right;\"> thinning </th>\n   <th style=\"text-align:right;\"> warmup </th>\n   <th style=\"text-align:left;\"> diverg_transitions </th>\n   <th style=\"text-align:left;\"> rhats &gt; 1.05 </th>\n   <th style=\"text-align:right;\"> min_bulk_ESS </th>\n   <th style=\"text-align:right;\"> min_tail_ESS </th>\n   <th style=\"text-align:left;\"> seed </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> b-normal(0, 2)\nsd-exponential(1)\nsigma-exponential(1) </td>\n   <td style=\"text-align:left;\"> acoustic_distance_sc ~ 0 + species + species:same_population + (1 | mm(pop1, pop2)) + (1 | mm(individual1, individual2)) </td>\n   <td style=\"text-align:right;\"> 10000 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 5000 </td>\n   <td style=\"text-align:left;\"> <span style=\" font-weight: bold;    color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: red !important;font-size: 12px;\">83 (0.0042%)</span> </td>\n   <td style=\"text-align:left;\"> <span style=\"     \">0</span> </td>\n   <td style=\"text-align:right;\"> 13314.17 </td>\n   <td style=\"text-align:right;\"> 11100.08 </td>\n   <td style=\"text-align:left;\"> 404934520 </td>\n  </tr>\n</tbody>\n</table><table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"font-size: 12px; width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:right;\"> Estimate </th>\n   <th style=\"text-align:right;\"> l-95% CI </th>\n   <th style=\"text-align:right;\"> u-95% CI </th>\n   <th style=\"text-align:left;\"> Rhat </th>\n   <th style=\"text-align:right;\"> Bulk_ESS </th>\n   <th style=\"text-align:right;\"> Tail_ESS </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> b_speciesHypoxantha </td>\n   <td style=\"text-align:right;\"> 0.092 </td>\n   <td style=\"text-align:right;\"> -0.650 </td>\n   <td style=\"text-align:right;\"> 0.857 </td>\n   <td style=\"text-align:left;\"> <span style=\"     \">1</span> </td>\n   <td style=\"text-align:right;\"> 13314.17 </td>\n   <td style=\"text-align:right;\"> 11215.52 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> b_speciesRuficollis </td>\n   <td style=\"text-align:right;\"> 0.144 </td>\n   <td style=\"text-align:right;\"> -0.490 </td>\n   <td style=\"text-align:right;\"> 0.804 </td>\n   <td style=\"text-align:left;\"> <span style=\"     \">1</span> </td>\n   <td style=\"text-align:right;\"> 14156.72 </td>\n   <td style=\"text-align:right;\"> 11100.08 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;background-color: rgba(109, 205, 89, 77) !important;\"> b_speciesHypoxantha:same_population1 </td>\n   <td style=\"text-align:right;background-color: rgba(109, 205, 89, 77) !important;\"> -0.164 </td>\n   <td style=\"text-align:right;background-color: rgba(109, 205, 89, 77) !important;\"> -0.197 </td>\n   <td style=\"text-align:right;background-color: rgba(109, 205, 89, 77) !important;\"> -0.131 </td>\n   <td style=\"text-align:left;background-color: rgba(109, 205, 89, 77) !important;\"> <span style=\"     \">1</span> </td>\n   <td style=\"text-align:right;background-color: rgba(109, 205, 89, 77) !important;\"> 26034.84 </td>\n   <td style=\"text-align:right;background-color: rgba(109, 205, 89, 77) !important;\"> 12043.28 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;background-color: rgba(109, 205, 89, 77) !important;\"> b_speciesRuficollis:same_population1 </td>\n   <td style=\"text-align:right;background-color: rgba(109, 205, 89, 77) !important;\"> -0.463 </td>\n   <td style=\"text-align:right;background-color: rgba(109, 205, 89, 77) !important;\"> -0.496 </td>\n   <td style=\"text-align:right;background-color: rgba(109, 205, 89, 77) !important;\"> -0.430 </td>\n   <td style=\"text-align:left;background-color: rgba(109, 205, 89, 77) !important;\"> <span style=\"     \">1</span> </td>\n   <td style=\"text-align:right;background-color: rgba(109, 205, 89, 77) !important;\"> 24907.92 </td>\n   <td style=\"text-align:right;background-color: rgba(109, 205, 89, 77) !important;\"> 12786.48 </td>\n  </tr>\n</tbody>\n</table>![](1_population_structure_files/figure-html/population structure summary model simple-1.png){width=672}\n\n## Model: isolation by distance among populations\n\nDoes acoustic distance between populations increase with geographic distance? We test this only on between-population pairs. Within populations, geographic distance is close to zero and almost perfectly confounded with the same-population term above.\n\n$$\n\\begin{split}\n\\text{acoustic distance} &\\sim \\text{species} + \\text{species} : \\text{geographic distance} \\\\\n&\\quad + (1 \\mid \\text{mm(population}_1,\\text{population}_2)) \\\\\n&\\quad + (1 \\mid \\text{mm(individual}_1,\\text{individual}_2))\n\\end{split}\n$$\n\nAcoustic distance and geographic distance are both standardized within this subset, with the same regularizing priors. Note that the number of population pairs is very small (3 for a species with 3 populations, 6 for one with 4), so the slope is informed by very few independent contrasts and should be read as descriptive.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nibd_dat_simple <- ps_model_dat_simple[ps_model_dat_simple$same_population == \"0\", ]\nibd_dat_simple$acoustic_distance_sc <- as.numeric(scale(ibd_dat_simple$acoustic_distance))\nibd_dat_simple$geo_distance_sc <- as.numeric(scale(ibd_dat_simple$geo_distance))\n\nibd_model_simple <- brm(\n  acoustic_distance_sc ~ species + species:geo_distance_sc +\n    (1 | mm(pop1, pop2)) +\n    (1 | mm(individual1, individual2)),\n  data = ibd_dat_simple,\n  family = gaussian(),\n  prior = priors_ws,\n  cores = 4,\n  chains = 4,\n  iter = 10000,\n  backend = \"cmdstanr\",\n  threads = threading(8),\n  control = list(adapt_delta = 0.95, max_treedepth = 15),\n  file = \"./data/processed/fits/isolation_by_distance_simple_fit\"\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprior_only_isolation_by_distance_simple <- brm(\n  acoustic_distance_sc ~ species + species:geo_distance_sc +\n    (1 | mm(pop1, pop2)) +\n    (1 | mm(individual1, individual2)),\n  data = ibd_dat_simple,\n  family = gaussian(),\n  prior = priors_ws,\n  sample_prior = \"only\",\n  chains = 2,\n  iter = 2000,\n  cores = 2,\n  seed = 123,\n  backend = \"cmdstanr\",\n  file = \"./data/processed/fits/prior_only_isolation_by_distance_simple\"\n)\n\nprior_check_plot(prior_only_isolation_by_distance_simple,\n                 \"Prior predictive check (simple songs, isolation by distance model)\")\n```\n\n::: {.cell-output-display}\n![](1_population_structure_files/figure-html/prior predictive check isolation by distance simple-1.png){width=672}\n:::\n:::\n\n\n\n```{.r .cell-code}\nextended_summary(\n  ibd_model_simple,\n  highlight = TRUE,\n  trace.palette = viridis::mako,\n  remove.intercepts = TRUE,\n  print.name = FALSE\n)\n```\n\n<table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"font-size: 12px; width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:left;\"> priors </th>\n   <th style=\"text-align:left;\"> formula </th>\n   <th style=\"text-align:right;\"> iterations </th>\n   <th style=\"text-align:right;\"> chains </th>\n   <th style=\"text-align:right;\"> thinning </th>\n   <th style=\"text-align:right;\"> warmup </th>\n   <th style=\"text-align:left;\"> diverg_transitions </th>\n   <th style=\"text-align:left;\"> rhats &gt; 1.05 </th>\n   <th style=\"text-align:right;\"> min_bulk_ESS </th>\n   <th style=\"text-align:right;\"> min_tail_ESS </th>\n   <th style=\"text-align:left;\"> seed </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> b-normal(0, 0.5)\nIntercept-normal(0, 1)\nsd-exponential(2)\nsigma-exponential(1) </td>\n   <td style=\"text-align:left;\"> acoustic_distance_sc ~ species + species:geo_distance_sc + (1 | mm(pop1, pop2)) + (1 | mm(individual1, individual2)) </td>\n   <td style=\"text-align:right;\"> 10000 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 5000 </td>\n   <td style=\"text-align:left;\"> <span style=\"     \">0 (0%)</span> </td>\n   <td style=\"text-align:left;\"> <span style=\"     \">0</span> </td>\n   <td style=\"text-align:right;\"> 22921.13 </td>\n   <td style=\"text-align:right;\"> 12871.01 </td>\n   <td style=\"text-align:left;\"> 1664082248 </td>\n  </tr>\n</tbody>\n</table><table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"font-size: 12px; width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:right;\"> Estimate </th>\n   <th style=\"text-align:right;\"> l-95% CI </th>\n   <th style=\"text-align:right;\"> u-95% CI </th>\n   <th style=\"text-align:left;\"> Rhat </th>\n   <th style=\"text-align:right;\"> Bulk_ESS </th>\n   <th style=\"text-align:right;\"> Tail_ESS </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> b_speciesRuficollis </td>\n   <td style=\"text-align:right;\"> 0.039 </td>\n   <td style=\"text-align:right;\"> -0.841 </td>\n   <td style=\"text-align:right;\"> 0.921 </td>\n   <td style=\"text-align:left;\"> <span style=\"     \">1</span> </td>\n   <td style=\"text-align:right;\"> 28698.06 </td>\n   <td style=\"text-align:right;\"> 14851.36 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> b_speciesHypoxantha:geo_distance_sc </td>\n   <td style=\"text-align:right;\"> -0.267 </td>\n   <td style=\"text-align:right;\"> -1.160 </td>\n   <td style=\"text-align:right;\"> 0.631 </td>\n   <td style=\"text-align:left;\"> <span style=\"     \">1</span> </td>\n   <td style=\"text-align:right;\"> 26001.27 </td>\n   <td style=\"text-align:right;\"> 13679.87 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;background-color: rgba(109, 205, 89, 77) !important;\"> b_speciesRuficollis:geo_distance_sc </td>\n   <td style=\"text-align:right;background-color: rgba(109, 205, 89, 77) !important;\"> -0.366 </td>\n   <td style=\"text-align:right;background-color: rgba(109, 205, 89, 77) !important;\"> -0.435 </td>\n   <td style=\"text-align:right;background-color: rgba(109, 205, 89, 77) !important;\"> -0.295 </td>\n   <td style=\"text-align:left;background-color: rgba(109, 205, 89, 77) !important;\"> <span style=\"     \">1</span> </td>\n   <td style=\"text-align:right;background-color: rgba(109, 205, 89, 77) !important;\"> 22921.13 </td>\n   <td style=\"text-align:right;background-color: rgba(109, 205, 89, 77) !important;\"> 12871.01 </td>\n  </tr>\n</tbody>\n</table>![](1_population_structure_files/figure-html/isolation by distance summary simple-1.png){width=672}\n\n::: {.alert .alert-info}\n## Summary {.unnumbered .unlisted}\n\n### Model summary {.unnumbered .unlisted}\n\n-   Within-population pairs are credibly more similar than between-population pairs for *Hypoxantha* (species:same_population1 = -0.164 SD, 95% CI [-0.197, -0.131]) and, more strongly, for *Ruficollis* (-0.463 SD, 95% CI [-0.496, -0.430]) — roughly a three-fold larger effect. Both models converged cleanly (Rhat = 1, no credible-interval-crossing issues).\n-   The isolation-by-distance slope is not credible for *Hypoxantha* (-0.267 SD, 95% CI [-1.160, 0.631]) but is credible and negative for *Ruficollis* (-0.366 SD, 95% CI [-0.435, -0.295]). With only 3-6 independent population pairs per species, this estimate is informed by very little independent replication and should be read as descriptive.\n\n### Interpretation {.unnumbered .unlisted}\n\n-   Simple songs carry genuine, population-level geographic structure in both species with more than one population, confirming there is local song variation for sympatry to act on in Step 3.\n-   The much stronger structuring in *Ruficollis* suggests either more restricted song learning/dispersal or more time for populations to diverge in that species than in *Hypoxantha*.\n-   The negative, rather than positive, isolation-by-distance trend in *Ruficollis* indicates that this population structure is not simply accumulating with geographic distance as under neutral drift — distant populations are not more acoustically different than nearby ones. This is consistent with song divergence being driven by local factors (habitat acoustics, drift in small founder populations, or selective pressures such as sympatry with congeners) rather than by isolation by distance per se, though the small number of population pairs means this should be treated as a hypothesis for the sympatry-focused steps rather than a confirmed result.\n:::\n\n# Complex songs\n\nRange-wide variation by species (`mean_within` and `mean_between` are mean acoustic distances among songs of different individuals within and between populations; the ratio is > 1 when songs are population-structured):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(population_structure_summary(ps_dat_complex))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div style=\"border: 1px solid #ddd; padding: 5px; overflow-x: scroll; width:100%; \"><table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> species </th>\n   <th style=\"text-align:right;\"> populations </th>\n   <th style=\"text-align:right;\"> individuals </th>\n   <th style=\"text-align:right;\"> within_population_pairs </th>\n   <th style=\"text-align:right;\"> between_population_pairs </th>\n   <th style=\"text-align:right;\"> mean_within </th>\n   <th style=\"text-align:right;\"> mean_between </th>\n   <th style=\"text-align:right;\"> between_within_ratio </th>\n   <th style=\"text-align:right;\"> max_geo_distance_km </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Hypoxantha </td>\n   <td style=\"text-align:right;\"> 3 </td>\n   <td style=\"text-align:right;\"> 24 </td>\n   <td style=\"text-align:right;\"> 2207 </td>\n   <td style=\"text-align:right;\"> 4717 </td>\n   <td style=\"text-align:right;\"> 2.219 </td>\n   <td style=\"text-align:right;\"> 2.130 </td>\n   <td style=\"text-align:right;\"> 0.960 </td>\n   <td style=\"text-align:right;\"> 583 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Iberaensis </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 6 </td>\n   <td style=\"text-align:right;\"> 446 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 2.575 </td>\n   <td style=\"text-align:right;\">  </td>\n   <td style=\"text-align:right;\">  </td>\n   <td style=\"text-align:right;\"> 1 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Palustris </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 29 </td>\n   <td style=\"text-align:right;\"> 13434 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 2.466 </td>\n   <td style=\"text-align:right;\">  </td>\n   <td style=\"text-align:right;\">  </td>\n   <td style=\"text-align:right;\"> 9 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Ruficollis </td>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:right;\"> 20 </td>\n   <td style=\"text-align:right;\"> 788 </td>\n   <td style=\"text-align:right;\"> 663 </td>\n   <td style=\"text-align:right;\"> 2.788 </td>\n   <td style=\"text-align:right;\"> 2.608 </td>\n   <td style=\"text-align:right;\"> 0.936 </td>\n   <td style=\"text-align:right;\"> 1159 </td>\n  </tr>\n</tbody>\n</table></div>\n\n`````\n:::\n:::\n\n\nSpecies sampled at a single locality only contribute within-population variation, so they are described above but not included in the models below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(ps_dat_complex, aes(x = same_population, y = acoustic_distance, fill = same_population)) +\n  geom_violin(alpha = 0.6, color = NA) +\n  geom_boxplot(width = 0.15, outlier.shape = NA, fill = \"white\") +\n  facet_wrap(~ species, nrow = 1) +\n  scale_x_discrete(labels = c(\"0\" = \"Between populations\", \"1\" = \"Within population\")) +\n  scale_fill_viridis_d(option = \"mako\", begin = 0.3, end = 0.8, guide = \"none\") +\n  labs(x = NULL, y = \"Acoustic distance\") +\n  theme(axis.text.x = element_text(size = rel(0.7), angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](1_population_structure_files/figure-html/population structure plot complex-1.png){width=672}\n:::\n:::\n\n\n## Model: within vs. between populations\n\n$$\n\\begin{split}\n\\text{acoustic distance} &\\sim \\text{species} + \\text{species} : \\text{same population} \\\\\n&\\quad + (1 \\mid \\text{mm(population}_1,\\text{population}_2)) \\\\\n&\\quad + (1 \\mid \\text{mm(individual}_1,\\text{individual}_2))\n\\end{split}\n$$\n\n-   Only conspecific pairs from species sampled in more than one population.\n-   `species:same_population1` is the species-specific difference in acoustic distance between within- and between-population pairs. Negative values mean songs are more similar within populations.\n-   Species enter as fixed effects because only two species have more than one population. The intercept is the baseline (between-population) distance of the reference species and `species` is the baseline difference of the other species. This parameterization keeps the regularizing prior on the effects and the baseline difference only, not on species means.\n-   Multi-membership random effects for population and individual, as in the sympatry models.\n-   The response is standardized within the model dataset (both species pooled), so effects are in SD units. Regularizing priors as in the trait-level sympatry models: normal(0, 1) for the intercept, normal(0, 0.5) for fixed effects, exponential(2) for random-effect SDs (including the multi-membership terms) and exponential(1) for the residual SD.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nps_model_dat_complex <- ps_dat_complex[\n  ps_dat_complex$species %in% names(occ_complex)[lengths(occ_complex) > 1], ]\nps_model_dat_complex$species <- droplevels(ps_model_dat_complex$species)\nps_model_dat_complex$acoustic_distance_sc <- as.numeric(scale(ps_model_dat_complex$acoustic_distance))\n\npopulation_structure_model_complex <- brm(\n  acoustic_distance_sc ~ species + species:same_population +\n    (1 | mm(pop1, pop2)) +\n    (1 | mm(individual1, individual2)),\n  data = ps_model_dat_complex,\n  family = gaussian(),\n  prior = priors_ws,\n  cores = 4,\n  chains = 4,\n  iter = 10000,\n  backend = \"cmdstanr\",\n  threads = threading(8),\n  control = list(adapt_delta = 0.95, max_treedepth = 15),\n  file = \"./data/processed/fits/population_structure_complex_fit\"\n)\n```\n:::\n\n\nPrior predictive check (priors only, likelihood ignored; the observed standardized distances should fall comfortably within the range the priors generate):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprior_only_population_structure_complex <- brm(\n  acoustic_distance_sc ~ species + species:same_population +\n    (1 | mm(pop1, pop2)) +\n    (1 | mm(individual1, individual2)),\n  data = ps_model_dat_complex,\n  family = gaussian(),\n  prior = priors_ws,\n  sample_prior = \"only\",\n  chains = 2,\n  iter = 2000,\n  cores = 2,\n  seed = 123,\n  backend = \"cmdstanr\",\n  file = \"./data/processed/fits/prior_only_population_structure_complex\"\n)\n\nprior_check_plot(prior_only_population_structure_complex,\n                 \"Prior predictive check (complex songs, population structure model)\")\n```\n\n::: {.cell-output-display}\n![](1_population_structure_files/figure-html/prior predictive check population structure complex-1.png){width=672}\n:::\n:::\n\n\n\n```{.r .cell-code}\nextended_summary(\n  population_structure_model_complex,\n  highlight = TRUE,\n  trace.palette = viridis::mako,\n  remove.intercepts = TRUE,\n  print.name = FALSE\n)\n```\n\n<table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"font-size: 12px; width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:left;\"> priors </th>\n   <th style=\"text-align:left;\"> formula </th>\n   <th style=\"text-align:right;\"> iterations </th>\n   <th style=\"text-align:right;\"> chains </th>\n   <th style=\"text-align:right;\"> thinning </th>\n   <th style=\"text-align:right;\"> warmup </th>\n   <th style=\"text-align:left;\"> diverg_transitions </th>\n   <th style=\"text-align:left;\"> rhats &gt; 1.05 </th>\n   <th style=\"text-align:right;\"> min_bulk_ESS </th>\n   <th style=\"text-align:right;\"> min_tail_ESS </th>\n   <th style=\"text-align:left;\"> seed </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> b-normal(0, 0.5)\nIntercept-normal(0, 1)\nsd-exponential(2)\nsigma-exponential(1) </td>\n   <td style=\"text-align:left;\"> acoustic_distance_sc ~ species + species:same_population + (1 | mm(pop1, pop2)) + (1 | mm(individual1, individual2)) </td>\n   <td style=\"text-align:right;\"> 10000 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 5000 </td>\n   <td style=\"text-align:left;\"> <span style=\" font-weight: bold;    color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: red !important;font-size: 12px;\">42 (0.0021%)</span> </td>\n   <td style=\"text-align:left;\"> <span style=\"     \">0</span> </td>\n   <td style=\"text-align:right;\"> 11005.74 </td>\n   <td style=\"text-align:right;\"> 12641.81 </td>\n   <td style=\"text-align:left;\"> 919127114 </td>\n  </tr>\n</tbody>\n</table><table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"font-size: 12px; width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:right;\"> Estimate </th>\n   <th style=\"text-align:right;\"> l-95% CI </th>\n   <th style=\"text-align:right;\"> u-95% CI </th>\n   <th style=\"text-align:left;\"> Rhat </th>\n   <th style=\"text-align:right;\"> Bulk_ESS </th>\n   <th style=\"text-align:right;\"> Tail_ESS </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> b_speciesRuficollis </td>\n   <td style=\"text-align:right;\"> 0.060 </td>\n   <td style=\"text-align:right;\"> -0.631 </td>\n   <td style=\"text-align:right;\"> 0.741 </td>\n   <td style=\"text-align:left;\"> <span style=\"     \">1</span> </td>\n   <td style=\"text-align:right;\"> 11005.74 </td>\n   <td style=\"text-align:right;\"> 12641.81 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> b_speciesHypoxantha:same_population1 </td>\n   <td style=\"text-align:right;\"> 0.019 </td>\n   <td style=\"text-align:right;\"> -0.028 </td>\n   <td style=\"text-align:right;\"> 0.065 </td>\n   <td style=\"text-align:left;\"> <span style=\"     \">1</span> </td>\n   <td style=\"text-align:right;\"> 20230.11 </td>\n   <td style=\"text-align:right;\"> 13767.58 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;background-color: rgba(109, 205, 89, 77) !important;\"> b_speciesRuficollis:same_population1 </td>\n   <td style=\"text-align:right;background-color: rgba(109, 205, 89, 77) !important;\"> -0.267 </td>\n   <td style=\"text-align:right;background-color: rgba(109, 205, 89, 77) !important;\"> -0.371 </td>\n   <td style=\"text-align:right;background-color: rgba(109, 205, 89, 77) !important;\"> -0.165 </td>\n   <td style=\"text-align:left;background-color: rgba(109, 205, 89, 77) !important;\"> <span style=\"     \">1</span> </td>\n   <td style=\"text-align:right;background-color: rgba(109, 205, 89, 77) !important;\"> 19693.62 </td>\n   <td style=\"text-align:right;background-color: rgba(109, 205, 89, 77) !important;\"> 13774.68 </td>\n  </tr>\n</tbody>\n</table>![](1_population_structure_files/figure-html/population structure summary model complex-1.png){width=672}\n\n## Model: isolation by distance among populations\n\nDoes acoustic distance between populations increase with geographic distance? We test this only on between-population pairs. Within populations, geographic distance is close to zero and almost perfectly confounded with the same-population term above.\n\n$$\n\\begin{split}\n\\text{acoustic distance} &\\sim \\text{species} + \\text{species} : \\text{geographic distance} \\\\\n&\\quad + (1 \\mid \\text{mm(population}_1,\\text{population}_2)) \\\\\n&\\quad + (1 \\mid \\text{mm(individual}_1,\\text{individual}_2))\n\\end{split}\n$$\n\nAcoustic distance and geographic distance are both standardized within this subset, with the same regularizing priors. Note that the number of population pairs is very small (3 for a species with 3 populations, 6 for one with 4), so the slope is informed by very few independent contrasts and should be read as descriptive.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nibd_dat_complex <- ps_model_dat_complex[ps_model_dat_complex$same_population == \"0\", ]\nibd_dat_complex$acoustic_distance_sc <- as.numeric(scale(ibd_dat_complex$acoustic_distance))\nibd_dat_complex$geo_distance_sc <- as.numeric(scale(ibd_dat_complex$geo_distance))\n\nibd_model_complex <- brm(\n  acoustic_distance_sc ~ species + species:geo_distance_sc +\n    (1 | mm(pop1, pop2)) +\n    (1 | mm(individual1, individual2)),\n  data = ibd_dat_complex,\n  family = gaussian(),\n  prior = priors_ws,\n  cores = 4,\n  chains = 4,\n  iter = 10000,\n  backend = \"cmdstanr\",\n  threads = threading(8),\n  control = list(adapt_delta = 0.95, max_treedepth = 15),\n  file = \"./data/processed/fits/isolation_by_distance_complex_fit\"\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprior_only_isolation_by_distance_complex <- brm(\n  acoustic_distance_sc ~ species + species:geo_distance_sc +\n    (1 | mm(pop1, pop2)) +\n    (1 | mm(individual1, individual2)),\n  data = ibd_dat_complex,\n  family = gaussian(),\n  prior = priors_ws,\n  sample_prior = \"only\",\n  chains = 2,\n  iter = 2000,\n  cores = 2,\n  seed = 123,\n  backend = \"cmdstanr\",\n  file = \"./data/processed/fits/prior_only_isolation_by_distance_complex\"\n)\n\nprior_check_plot(prior_only_isolation_by_distance_complex,\n                 \"Prior predictive check (complex songs, isolation by distance model)\")\n```\n\n::: {.cell-output-display}\n![](1_population_structure_files/figure-html/prior predictive check isolation by distance complex-1.png){width=672}\n:::\n:::\n\n\n\n```{.r .cell-code}\nextended_summary(\n  ibd_model_complex,\n  highlight = TRUE,\n  trace.palette = viridis::mako,\n  remove.intercepts = TRUE,\n  print.name = FALSE\n)\n```\n\n<table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"font-size: 12px; width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:left;\"> priors </th>\n   <th style=\"text-align:left;\"> formula </th>\n   <th style=\"text-align:right;\"> iterations </th>\n   <th style=\"text-align:right;\"> chains </th>\n   <th style=\"text-align:right;\"> thinning </th>\n   <th style=\"text-align:right;\"> warmup </th>\n   <th style=\"text-align:left;\"> diverg_transitions </th>\n   <th style=\"text-align:left;\"> rhats &gt; 1.05 </th>\n   <th style=\"text-align:right;\"> min_bulk_ESS </th>\n   <th style=\"text-align:right;\"> min_tail_ESS </th>\n   <th style=\"text-align:left;\"> seed </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> b-normal(0, 2)\nsd-exponential(1)\nsigma-exponential(1) </td>\n   <td style=\"text-align:left;\"> acoustic_distance_sc ~ 0 + species + species:geo_distance_sc + (1 | mm(pop1, pop2)) + (1 | mm(individual1, individual2)) </td>\n   <td style=\"text-align:right;\"> 10000 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 5000 </td>\n   <td style=\"text-align:left;\"> <span style=\" font-weight: bold;    color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: red !important;font-size: 12px;\">119 (0.006%)</span> </td>\n   <td style=\"text-align:left;\"> <span style=\"     \">0</span> </td>\n   <td style=\"text-align:right;\"> 6969.971 </td>\n   <td style=\"text-align:right;\"> 6856.707 </td>\n   <td style=\"text-align:left;\"> 43127574 </td>\n  </tr>\n</tbody>\n</table><table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"font-size: 12px; width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:right;\"> Estimate </th>\n   <th style=\"text-align:right;\"> l-95% CI </th>\n   <th style=\"text-align:right;\"> u-95% CI </th>\n   <th style=\"text-align:left;\"> Rhat </th>\n   <th style=\"text-align:right;\"> Bulk_ESS </th>\n   <th style=\"text-align:right;\"> Tail_ESS </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> b_speciesHypoxantha </td>\n   <td style=\"text-align:right;\"> -0.164 </td>\n   <td style=\"text-align:right;\"> -1.323 </td>\n   <td style=\"text-align:right;\"> 0.799 </td>\n   <td style=\"text-align:left;\"> <span style=\"     \">1.001</span> </td>\n   <td style=\"text-align:right;\"> 6969.971 </td>\n   <td style=\"text-align:right;\"> 6856.707 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> b_speciesRuficollis </td>\n   <td style=\"text-align:right;\"> 0.250 </td>\n   <td style=\"text-align:right;\"> -3.179 </td>\n   <td style=\"text-align:right;\"> 3.758 </td>\n   <td style=\"text-align:left;\"> <span style=\"     \">1</span> </td>\n   <td style=\"text-align:right;\"> 13778.602 </td>\n   <td style=\"text-align:right;\"> 13177.876 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> b_speciesHypoxantha:geo_distance_sc </td>\n   <td style=\"text-align:right;\"> -0.889 </td>\n   <td style=\"text-align:right;\"> -2.671 </td>\n   <td style=\"text-align:right;\"> 0.428 </td>\n   <td style=\"text-align:left;\"> <span style=\"     \">1.001</span> </td>\n   <td style=\"text-align:right;\"> 8676.816 </td>\n   <td style=\"text-align:right;\"> 10141.405 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> b_speciesRuficollis:geo_distance_sc </td>\n   <td style=\"text-align:right;\"> -0.030 </td>\n   <td style=\"text-align:right;\"> -1.388 </td>\n   <td style=\"text-align:right;\"> 1.327 </td>\n   <td style=\"text-align:left;\"> <span style=\"     \">1</span> </td>\n   <td style=\"text-align:right;\"> 13013.693 </td>\n   <td style=\"text-align:right;\"> 12827.670 </td>\n  </tr>\n</tbody>\n</table>![](1_population_structure_files/figure-html/isolation by distance summary complex-1.png){width=672}\n\n::: {.alert .alert-info}\n## Summary {.unnumbered .unlisted}\n\n### Model summary {.unnumbered .unlisted}\n\n-   The within- vs. between-population effect is not credible for *Hypoxantha* (0.019 SD, 95% CI [-0.028, 0.065], overlapping zero and even slightly positive in direction) and is credible but smaller than in simple songs for *Ruficollis* (-0.267 SD, 95% CI [-0.371, -0.165]).\n-   Isolation by distance is not credible for either species (*Hypoxantha*: -0.889 SD, 95% CI [-2.671, 0.428]; *Ruficollis*: -0.030 SD, 95% CI [-1.388, 1.327]), with very wide intervals reflecting the small number of independent population pairs.\n\n### Interpretation {.unnumbered .unlisted}\n\n-   Unlike simple songs, complex songs carry little to no detectable population-level geographic signal in *Hypoxantha*, and a weaker signal than simple songs in *Ruficollis*.\n-   This asymmetry suggests complex songs are more stereotyped/conserved across each species' range — plausibly because they are under stronger stabilizing selection (e.g., species or mate recognition), are more constrained by shared motor templates, or are simply noisier measurements given fewer recordings per population.\n-   Practically, Step 3's test for sympatry-driven shifts has much less population-level variation to work with for complex songs than for simple songs, so any sympatry effect detected later for complex songs is acting on a flatter geographic baseline.\n:::\n\n<!-- add packages used, system details and versions  -->\n\n::: {.callout-note collapse=\"true\"}\n## Session information {.unnumbered .unlisted}\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n─ Session info ───────────────────────────────────────────────────────────────\n setting  value\n version  R version 4.5.2 (2025-10-31)\n os       Ubuntu 22.04.4 LTS\n system   x86_64, linux-gnu\n ui       X11\n language (EN)\n collate  en_US.UTF-8\n ctype    en_US.UTF-8\n tz       America/Costa_Rica\n date     2026-10-08\n pandoc   3.8.3 @ /usr/lib/rstudio/resources/app/bin/quarto/bin/tools/x86_64/ (via rmarkdown)\n quarto   1.9.38 @ /usr/lib/rstudio/resources/app/bin/quarto/bin/quarto\n\n─ Packages ───────────────────────────────────────────────────────────────────\n package        * version  date (UTC) lib source\n abind            1.4-8    2024-09-12 [1] CRAN (R 4.5.2)\n ape              5.8-1    2024-12-16 [1] CRAN (R 4.5.2)\n arrayhelpers     1.1-0    2020-02-04 [1] CRAN (R 4.5.2)\n backports        1.5.1    2026-04-03 [1] CRAN (R 4.5.2)\n bayesplot        1.15.0   2025-12-12 [1] CRAN (R 4.5.2)\n bridgesampling   1.2-1    2025-11-19 [1] CRAN (R 4.5.2)\n brms           * 2.23.0   2025-09-09 [1] CRAN (R 4.5.2)\n brmsish        * 1.0.0    2026-03-03 [1] Github (maRce10/brmsish@81ab826)\n Brobdingnag      1.2-9    2022-10-19 [1] CRAN (R 4.5.2)\n cachem           1.1.0    2024-05-16 [1] CRAN (R 4.5.2)\n checkmate        2.3.4    2026-02-03 [1] CRAN (R 4.5.2)\n cli              3.6.6    2026-04-09 [1] CRAN (R 4.5.2)\n cluster          2.1.8.2  2026-02-05 [1] CRAN (R 4.5.2)\n cmdstanr       * 0.9.0    2025-03-30 [1] https://stan-dev.r-universe.dev (R 4.5.2)\n coda             0.19-4.1 2024-01-31 [1] CRAN (R 4.5.2)\n codetools        0.2-20   2024-03-31 [1] CRAN (R 4.5.2)\n cowplot          1.2.0    2025-07-07 [1] CRAN (R 4.5.2)\n crayon           1.5.3    2024-06-20 [1] CRAN (R 4.5.2)\n curl             8.0.0    2026-08-25 [1] CRAN (R 4.5.2)\n devtools         2.4.6    2025-10-03 [1] CRAN (R 4.5.2)\n digest           0.6.39   2025-11-19 [1] CRAN (R 4.5.2)\n distributional   0.6.0    2026-01-14 [1] CRAN (R 4.5.2)\n dplyr          * 1.2.1    2026-04-03 [1] CRAN (R 4.5.2)\n ecodist        * 2.1.3    2023-10-30 [1] CRAN (R 4.5.2)\n ellipsis         0.3.2    2021-04-29 [3] CRAN (R 4.1.1)\n emmeans          2.0.4    2026-07-15 [1] CRAN (R 4.5.2)\n estimability     2.0.0    2026-06-26 [1] CRAN (R 4.5.2)\n evaluate         1.0.5    2025-08-27 [1] CRAN (R 4.5.2)\n farver           2.1.2    2024-05-13 [1] CRAN (R 4.5.2)\n fastmap          1.2.0    2024-05-15 [1] CRAN (R 4.5.2)\n forcats        * 1.0.1    2025-09-25 [1] CRAN (R 4.5.2)\n fs               2.1.0    2026-04-18 [1] CRAN (R 4.5.2)\n generics         0.1.4    2025-05-09 [1] CRAN (R 4.5.2)\n ggdist           3.3.3    2025-04-23 [1] CRAN (R 4.5.2)\n ggh4x          * 0.3.1    2025-05-30 [1] CRAN (R 4.5.2)\n ggplot2        * 4.0.3    2026-04-22 [1] CRAN (R 4.5.2)\n ggtext         * 0.1.2    2022-09-16 [1] CRAN (R 4.5.2)\n glue             1.8.1    2026-04-17 [1] CRAN (R 4.5.2)\n gridExtra        2.3.1    2026-06-25 [1] CRAN (R 4.5.2)\n gridtext         0.1.6    2026-02-19 [1] CRAN (R 4.5.2)\n gtable           0.3.6    2024-10-25 [1] CRAN (R 4.5.2)\n hms              1.1.4    2025-10-17 [1] CRAN (R 4.5.2)\n htmltools        0.5.9    2025-12-04 [1] CRAN (R 4.5.2)\n htmlwidgets      1.6.4    2023-12-06 [1] CRAN (R 4.5.2)\n igraph           2.3.3    2026-06-26 [1] CRAN (R 4.5.2)\n inline           0.3.21   2025-01-09 [1] CRAN (R 4.5.2)\n jsonlite         2.0.0    2025-03-27 [1] CRAN (R 4.5.2)\n kableExtra     * 1.4.0    2024-01-24 [1] CRAN (R 4.5.2)\n knitr          * 1.52     2026-09-06 [1] CRAN (R 4.5.2)\n labeling         0.4.3    2023-08-29 [1] CRAN (R 4.5.2)\n lattice          0.22-9   2026-02-09 [1] CRAN (R 4.5.2)\n lifecycle        1.0.5    2026-01-08 [1] CRAN (R 4.5.2)\n loo              2.9.0    2025-12-23 [1] CRAN (R 4.5.2)\n lubridate      * 1.9.5    2026-02-04 [1] CRAN (R 4.5.2)\n magrittr         2.0.5    2026-04-04 [1] CRAN (R 4.5.2)\n MASS             7.3-65   2025-02-28 [1] CRAN (R 4.5.2)\n Matrix           1.7-4    2025-08-28 [1] CRAN (R 4.5.2)\n matrixStats      1.5.0    2025-01-07 [1] CRAN (R 4.5.2)\n memoise          2.0.1    2021-11-26 [3] CRAN (R 4.1.2)\n mgcv             1.9-4    2025-11-07 [1] CRAN (R 4.5.2)\n multcomp         1.4-29   2025-10-20 [1] CRAN (R 4.5.2)\n mvtnorm          1.3-3    2025-01-10 [1] CRAN (R 4.5.2)\n nlme             3.1-168  2025-03-31 [1] CRAN (R 4.5.2)\n otel             0.2.0    2025-08-29 [1] CRAN (R 4.5.2)\n pbapply          1.7-5    2026-09-01 [1] CRAN (R 4.5.2)\n permute        * 0.9-10   2026-02-06 [1] CRAN (R 4.5.2)\n pillar           1.11.1   2025-09-17 [1] CRAN (R 4.5.2)\n pkgbuild         1.4.8    2025-05-26 [1] CRAN (R 4.5.2)\n pkgconfig        2.0.3    2019-09-22 [3] CRAN (R 4.0.1)\n pkgload          1.5.3    2026-06-15 [1] CRAN (R 4.5.2)\n plyr             1.8.9    2023-10-02 [1] CRAN (R 4.5.2)\n posterior        1.6.1    2025-02-27 [1] CRAN (R 4.5.2)\n processx         3.9.0    2026-04-22 [1] CRAN (R 4.5.2)\n ps               1.9.3    2026-04-20 [1] CRAN (R 4.5.2)\n purrr          * 1.2.2    2026-04-10 [1] CRAN (R 4.5.2)\n QuickJSR         1.9.0    2026-01-25 [1] CRAN (R 4.5.2)\n R6               2.6.1    2025-02-15 [1] CRAN (R 4.5.2)\n RColorBrewer     1.1-3    2022-04-03 [1] CRAN (R 4.5.2)\n Rcpp           * 1.1.2    2026-07-05 [1] CRAN (R 4.5.2)\n RcppParallel     5.1.11-2 2026-03-05 [1] CRAN (R 4.5.2)\n readr          * 2.2.0    2026-02-19 [1] CRAN (R 4.5.2)\n remotes          2.5.0    2024-03-17 [1] CRAN (R 4.5.2)\n reshape2         1.4.5    2025-11-12 [1] CRAN (R 4.5.2)\n rlang            1.3.0    2026-07-05 [1] CRAN (R 4.5.2)\n rmarkdown        2.32     2026-09-01 [1] CRAN (R 4.5.2)\n rstan            2.32.7   2025-03-10 [1] CRAN (R 4.5.2)\n rstantools       2.6.0    2026-01-10 [1] CRAN (R 4.5.2)\n rstudioapi       0.18.0   2026-01-16 [1] CRAN (R 4.5.2)\n S7               0.2.2    2026-04-22 [1] CRAN (R 4.5.2)\n sandwich         3.1-1    2024-09-15 [1] CRAN (R 4.5.2)\n scales           1.4.0    2025-04-24 [1] CRAN (R 4.5.2)\n sessioninfo      1.2.3    2025-02-05 [1] CRAN (R 4.5.2)\n sketchy          1.0.6    2026-10-08 [1] local (/home/m/Dropbox/R_package_testing/sketchy)\n StanHeaders      2.32.10  2024-07-15 [1] CRAN (R 4.5.2)\n stringi          1.8.9    2026-08-04 [1] CRAN (R 4.5.2)\n stringr        * 1.6.0    2025-11-04 [1] CRAN (R 4.5.2)\n survival         3.8-6    2026-01-16 [1] CRAN (R 4.5.2)\n svglite          2.2.2    2025-10-21 [1] CRAN (R 4.5.2)\n svUnit           1.0.8    2025-08-26 [1] CRAN (R 4.5.2)\n systemfonts      1.3.1    2025-10-01 [1] CRAN (R 4.5.2)\n tensorA          0.36.2.1 2023-12-13 [1] CRAN (R 4.5.2)\n textshaping      1.0.4    2025-10-10 [1] CRAN (R 4.5.2)\n TH.data          1.1-5    2025-11-17 [1] CRAN (R 4.5.2)\n tibble         * 3.3.1    2026-01-11 [1] CRAN (R 4.5.2)\n tidybayes        3.0.7    2024-09-15 [1] CRAN (R 4.5.2)\n tidyr          * 1.3.2    2025-12-19 [1] CRAN (R 4.5.2)\n tidyselect       1.2.1    2024-03-11 [1] CRAN (R 4.5.2)\n tidyverse      * 2.0.0    2023-02-22 [1] CRAN (R 4.5.2)\n timechange       0.4.0    2026-01-29 [1] CRAN (R 4.5.2)\n tzdb             0.5.0    2025-03-15 [1] CRAN (R 4.5.2)\n usethis          3.2.1    2025-09-06 [1] CRAN (R 4.5.2)\n V8               8.2.0    2026-04-21 [1] CRAN (R 4.5.2)\n vctrs            0.7.3    2026-04-11 [1] CRAN (R 4.5.2)\n vegan          * 2.7-5    2026-05-25 [1] CRAN (R 4.5.2)\n viridis          0.6.5    2024-01-29 [1] CRAN (R 4.5.2)\n viridisLite      0.4.3    2026-02-04 [1] CRAN (R 4.5.2)\n withr            3.0.3    2026-06-19 [1] CRAN (R 4.5.2)\n xfun             0.61     2026-09-16 [1] CRAN (R 4.5.2)\n xml2             1.6.0    2026-06-22 [1] CRAN (R 4.5.2)\n xtable           1.8-8    2026-02-22 [1] CRAN (R 4.5.2)\n yaml             2.3.12   2025-12-10 [1] CRAN (R 4.5.2)\n zoo              1.8-15   2025-12-15 [1] CRAN (R 4.5.2)\n\n [1] /home/m/R/x86_64-pc-linux-gnu-library/4.5\n [2] /usr/local/lib/R/site-library\n [3] /usr/lib/R/site-library\n [4] /usr/lib/R/library\n * ── Packages attached to the search path.\n\n──────────────────────────────────────────────────────────────────────────────\n```\n\n\n:::\n:::\n\n:::\n",
    "supporting": [
      "1_population_structure_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}